global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: flask-app
    static_configs:
      - targets: ["web:5000"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
